server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pokemonusers
#          jwk-set-uri: http://localhost:8080/realms/pokemonusers/protocol/openid-connect/certs